# Copyright (c) 2025 Roberta De Viti <rdeviti-at-mpi-sws.org> 
# Author: Roberta De Viti 
# SPDX-License-Identifier: MIT
# 
# Parse logs generated by ag2pc and calculate mean and standard deviation of times.

import csv
import numpy as np
import sys

def parse_sort_time(file_path, tile_size=10000, prefix=""):
    """
    Parses the log file, computes the mean and standard deviation for the "sort (32bit)" column
    for a specific tile_size, and writes the result to a new CSV file.

    Args:
        file_path (str): Path to the log file.
        tile_size (int): Tile size to filter by. Default is 10000.
        prefix (str): Prefix for the output file name (e.g., sh2pc, dualex). Default is "".

    Returns:
        None
    """

    sort_times = []

    # Read input file
    try:
        with open(file_path, 'r') as file:
            reader = csv.DictReader(file)
            for row in reader:
                if int(row['tile_size']) == tile_size:
                    sort_times.append(float(row['sort (32bit)']))
    except FileNotFoundError:
        print(f"Error: File {input_file} not found.")
        sys.exit(1)
    except IOError as e:
        print(f"Error reading file {input_file}: {e}")
        sys.exit(1)

    # Compute mean and standard deviation
    if sort_times:
        mean_time = np.mean(sort_times)
        stddev = np.std(sort_times)

        # Write the result to a CSV file
        output_file = f"{prefix}sort{tile_size}_time.csv"
        with open(output_file, 'w', newline='') as out_file:
            writer = csv.writer(out_file)
            writer.writerow([mean_time, stddev])
            print(f"Mean ({mean_time} seconds) and std dev ({stddev} seconds) written to '{output_file}'.")

    else:
        print(f"No data found for tile_size {tile_size}.")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python sh2pc_parser.py <input_file> [<file_name_prefix>]")
        sys.exit(1)

    input_file = sys.argv[1]
    file_name_prefix = sys.argv[2]
    parse_sort_time(input_file, tile_size=10000, prefix=file_name_prefix)
